### ISSUE TITLE
E-mail credentials i ENV var

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/auto-bankposteringer-nordea-kmdopus#23]
Opdater konfigurationsnode til mail-modul med credentials fra ENV var med `${ENV_VAR}` jf. https://nodered.org/docs/user-guide/environment-variables

**Comment by CSL-randers** [comment]
Ikke nødvendigt, da der ikke er behov for credentials når KIT hoster programmet
