### ISSUE TITLE
Knap til aktivering/deaktivering af regler

### ISSUE THREAD

**Issue by CSL-randers** [Randers-Kommune-Digitalisering/auto-bankposteringer-nordea-kmdopus#26]
I [RetKonteringsregel.vue](https://github.com/Randers-Kommune-Digitalisering/auto-bankposteringer-nordea-kmdopus/vue/src/views/RetKonteringsregel.vue) har jeg forsøgt at tilføje en knap til at toggle Active property'en i konteringsreglen. Af en eller anden årsag bliver værdien dog ved med at være null, ligemeget hvordan jeg stiller koden op.

**Comment by st-randers** [comment]
Løst i https://github.com/Randers-Kommune-Digitalisering/auto-bankposteringer-nordea-kmdopus/tree/rule-toggle-active
